add_newline = false
format = "$username$hostname$directory$git_branch$git_state$git_status$cmd_duration$character"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

# minimal branch
[git_branch]
symbol = ""
format = "[\\($branch\\)]($style) "

[cmd_duration]
format = "[⌚$duration]($style) "
