add_newline = false
prompt_order = [
  "username",
  "hostname",
  "directory",
  "git_branch",
  "git_state",
  "git_status",
  "cmd_duration",
  "character"
]

[character]
symbol = ">"

# minimal branch
[git_branch]
symbol = ""
prefix = "("
suffix = ")"

[cmd_duration]
prefix = "⌚"
